version: "3.8"

services:
  backoffice:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backoffice
    ports:
      - 8000:8000
    volumes:
      - .:/app

  mysql:
    image: mysql:8
    container_name: mysql2
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=Backoffice
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./mysql:/var/lib/mysql
